[profile.default]
src = "src"
libs = ["dependencies"]
evm_version = 'cancun'
solc = "0.8.28"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read-write", path = "./" }]
optimizer = true
optimizer_runs = 2000
# Only show coverage for files that do not match the specified regex pattern.
no_match_coverage = "test/mocks/**|script/**"

remappings = [
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.2.0/",
    "@openzeppelin/contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.2.0/",
    "@chainlink/contracts/=dependencies/@chainlink-contracts-0.8.0/",
    "@uniswap/v3-periphery/=dependencies/uniswap-v3-periphery-1.3.0/",
    "@uniswap/v3-core/=dependencies/uniswap-v3-periphery-1.3.0/node_modules/@uniswap/v3-core/",
]

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.2.0"
"@openzeppelin-contracts-upgradeable" = "5.2.0"
openzeppelin-foundry-upgrades = "0.4.0"
"@chainlink-contracts" = "0.8.0"
uniswap-v3-periphery = { version = "1.3.0", git = "https://github.com/Uniswap/v3-periphery.git", rev = "0682387198a24c7cd63566a2c58398533860a5d1" }

[fuzz]
runs = 20000
